version: "3.8"

services:
  db:
    image: postgres:16
    container_name: taskdb
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - taskdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./taskmanagerbackend
      dockerfile: Dockerfile
    container_name: task-backend
    restart: unless-stopped
    # if you connect to local postgreSQL just comment 3 line in down and add this to DB_URL jdbc:postgresql://host.docker.internal:5432/taskdb
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/taskdb
      DB_USERNAME: postgres
      DB_PASSWORD: changeme
      JWT_SECRET: replace_with_your_own_generated_secret
      DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  taskdb_data:
